### ISSUE TITLE
Tried to get this running but got various "Module build failed: TypeError: Cannot read property 'type' of undefined" errors (one per theme?)

### ISSUE THREAD

**Issue by sole** [devtools-html/reps#75] opened 2017-02-13 16:34 UTC
I did this without instructions, trying to guess what to do:

1. Cloned the repo
2. cd to repo
3. npm install
4. npm start

It kind of starts and shows this message:

```
reps sole$ npm run start

> devtools-reps@0.1.0 start /Users/sole/data/current/devtools/reps
> node bin/dev-server.js

Listening for WS on *:9000. Will proxy to TCP on *:6080 on first WS connection
Protocol messages can be logged by enabling logging.firefoxProtocol in your local.json config
Development Server Listening at http://localhost:8000
```

And after some seconds... The Stack Trace: https://gist.github.com/juliandescottes/1e8d96f89c8a3ee17228e7c4a5f91bc1

**Comment by juliandescottes** [comment] 2017-02-13 16:55
(moved the stacktrace to a gist) 

I just reproduced your issue! It fails when doing `npm install ; npm start` and works when doing `yarn install ; yarn start`. I'll have a look!

**Comment by juliandescottes** [comment] 2017-02-14 12:44
Turns out the issue comes from devtools-launchpad dependencies related to postcss.

I released a new version of launchpad (v0.0.43) which seems to fix the issue for me ... I didn't have time to really understand where the issue came from.

For the record `yarn` prevented the issue because our yarn.lock points to older versions of postcss dependencies. But today I tried using the inspector (who had no prior yarn.lock file) and `yarn install ; yarn start` failed in the same way as npm (because it fetched the latest dependencies).

In the latest version of launchpad I released, I didn't freeze/change any dependency, so I'm not sure why this has any impact :/

**Comment by juliandescottes** [comment] 2017-02-14 12:48
@sole just updated reps to use the latest launchpad. In any case we should recommend using yarn as it avoids having this kind of issues when we are not changing any dependency (which is obviously the when you are just a new user cloning the repo!)

**Comment by juliandescottes** [comment] 2017-02-16 17:22
I think this is now fixed, I will just update the readme to remove mentions of npm.

**Closed by juliandescottes** 2017-02-16 17:22 UTC
